config/routes.rb
Rails.application.routes.draw do
  get '/inicio', to: 'inicio#index'
  post '/inicio', to: 'inicio#index'
  get 'export_users', to: 'inicio#export_users', as: :export_users
 
  root to: 'inicio#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/borrado.rb
class Borrado < ApplicationRecord
end

app/models/xvideo.rb
require 'activerecord-import/base'
require 'activerecord-import/active_record/adapters/mysql2_adapter'
class Xvideo < ApplicationRecord
    def self.cargar_csv(videos)
        Xvideo.import videos, recursive: true
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buscador_controller.rb
class BuscadorController < ApplicationController
  def index
    @busca = Xvideo.search(params[:search])
    if @busca
      @mostrar = @busca
    end
  end

  def new
    
  end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
    
  end
  def export_users
    @job = Delayed::Job.enqueue ImportarJob.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buscador_helper.rb
module BuscadorHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/views/buscador/index.html.erb
<h1>Buscador#index</h1>
  <%= form_tag buscador_path, :method => 'post' do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
      </p>
  <% end %>
    <a href="<%= @mostrar %>"><%= @mostrar %></a>

app/views/inicio/export_users.js.haml
:plain
  var interval;
  $('.export .well').show();
  interval = setInterval(function(){
  $.ajax({
      url: '/progress-job/' + #{@job.id},
      success: function(job){
        var progress;
        // If there are errors
        if (job.last_error != null) {
          $('.progress-status').addClass('text-danger').text(job.progress_stage);
          $('.progress-bar').addClass('progress-bar-danger');
          $('.progress').removeClass('active');
          clearInterval(interval);
        }
        else{
            progress = job.progress_current / job.progress_max * 100;
            // In job stage
            if (progress.toString() !== 'NaN'){
              $('.progress-status').text(job.progress_current + '/' + job.progress_max);
              $('.progress-bar').css('width', progress + '%').text(progress + '%');
            }
            if (progress == 100){
              clearInterval(interval);
            }
        }
      },
      error: function(){
        // Job is no loger in database which means it finished successfuly
        $('.progress').removeClass('active');
        $('.progress-bar').css('width', '100%').text('100%');
        $('.progress-status').text('Se cargaron todos los registros del CSV');
        $('.export-link').show();
        clearInterval(interval);
      }
    })
  },1000);

app/views/inicio/index.html.haml
.export
  = link_to 'Importar CSV', export_users_path, remote: true, class: 'btn btn-primary btn-lg'
  .well{style: 'display:none'}
    .row
      .col-xs-12
        .progress-status.text-primary
    .row
      .col-xs-12
        .progress.progress-striped.active
          .progress-bar
            .text-primary
              0%

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCSV</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <!-- Agregados flash messages -->
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <!-- @@@@@@@@@@@@@@@@@@@@@@@@ --> 
      <%= yield %>
    </div>
  </body>
</html>